server:
  port: 8082
spring:
  application:
    name: airport
  datasource:
    url: jdbc:mysql://localhost:3306/AirportDb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update